### PR TITLE
First version of probe for alpine

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
Hello,

I propose this to help fixing alpine probe.
It is based on informations taken from : 
- https://musl.libc.org/doc/1.1.24/manual.html for include dirs and lib dirs
- https://pkgs.alpinelinux.org/contents?path=*pkgconfig*&page=1&file=*&branch=edge&name=* for pkgconfig dirs
- testing (with alpine, scottw/alpine-perl and i386/alpine)

I have a build OK for this code : https://github.com/thibaultduponchelle/aliens-ci/actions/runs/107958469

I'm not 100% sure about the correctness of this.

Regards.

Thibault

### CODE REVIEW

**Comment by plicease** [comment]
Awesome.  Can you please add `CIP_TAG=5.30-alpine3.9` to to the list of jobs in .travis.yml.  That will add alpine to ci.

**Comment by thibaultduponchelle** [comment]
> Awesome. Can you please add `CIP_TAG=5.30-alpine3.9` to to the list of jobs in .travis.yml. That will add alpine to ci.

:smiley: 

Done and build is green

I was not aware of this https://github.com/plicease/cip/blob/master/base/versions/alpine3.9/Dockerfile, seems like verything was already there for testing :)

**Comment by plicease** [comment]
> I was not aware of this https://github.com/plicease/cip/blob/master/base/versions/alpine3.9/Dockerfile, seems like verything was already there for testing :)

Yup.  I'm using it in Alien::Build for CI since it is potentially distro sensitive, but it makes sense to use it here too.  Can you add the fedora image as well: `5.30-fedora29` I think it should already work, but we should add support if not.  I don't think it makes sense to add centos (RHEL), since it is close enough to fedora for this.

**Comment by thibaultduponchelle** [comment]
Added ! :smiley:

**Comment by plicease** [comment]
Thanks.  This is going out along with 0.17.

**Pull request merged**
